// ---------------------------------------------------------------------------
// Revenue configuration.
//
// Everything here is OFF until filled in, and the site degrades cleanly when it
// is: no broken links, no dead buttons, no paywall. Fill a value, commit, and
// that revenue path turns on. Nothing else needs to change.
// ---------------------------------------------------------------------------

export const CONFIG = {
  // ---- Crypto payment (no KYC, no processor, no account) -----------------
  //
  // Buyers send USDC directly to this wallet. The browser verifies the transfer
  // against a public block explorer. Nothing is held by anyone in between.
  //
  // *** SET THIS TO A WALLET YOU HOLD THE PRIVATE KEY FOR. ***
  // Payments are irreversible. Two addresses appear in this workspace and they
  // are NOT interchangeable:
  //   0x26e967c1e708aC62Ebe6BF66f51061E555fc6ebd  - auto-generated by
  //       x402-seller/wallet.json on this machine (key is in that file)
  //   0x72B944dA66263bE35c2a2eDFeF5c525d58fa53Df  - recorded in project notes,
  //       presumably set as PAY_TO in the Render environment
  // If neither is a wallet you actually control, use your own address instead.
  //
  // SET TO 0x26e967... because it is *verified* controllable: its private key is
  // in x402-seller/wallet.json on this machine, and that file is gitignored and
  // was never committed, so the key is not exposed despite the repo being public.
  //
  // Two caveats worth acting on:
  //  1. It is an auto-generated hot wallet with a plaintext key on one machine.
  //     Fine for small revenue; move to a wallet you actively custody before
  //     any real balance accumulates.
  //  2. Change this line to any address you prefer - nothing else needs editing.
  cryptoAddress: '0x26e967c1e708aC62Ebe6BF66f51061E555fc6ebd',

  // 'base' is the right default: USDC transfers cost a fraction of a cent.
  // Also supported: 'ethereum', 'optimism'.
  chain: 'base',

  // Base price in USD. A unique cent value is added per invoice so each payment
  // is self-identifying without a backend - see src/payments.js.
  basePrice: 2,

  // How long an unlock lasts, in days.
  unlockDays: 30,

  // ---- Free tier ---------------------------------------------------------
  // Kept genuinely useful on purpose. The free results are the marketing: they
  // prove the tool works before anyone is asked to pay, and they are what search
  // engines and shared links land on.
  freePreviewResults: 5,
  freeMaxResults: 25,

  // ---- Apify (card payments - requires KYC, currently unused) -------------
  apifyActorUrl: '',
  proFeatures: [
    'Up to 300 opportunities per scan, not 25',
    'CSV and JSON export straight into your spreadsheet or CRM',
    'Scheduled daily or weekly scans that run without you',
    'Email alerts the moment a grant you are eligible for is posted',
    'API access for your own tooling',
  ],
};

export const hasCrypto = () => /^0x[a-fA-F0-9]{40}$/.test(CONFIG.cryptoAddress || '');
export const hasPro = () => Boolean(CONFIG.apifyActorUrl);
